// JSON

var jsonD = {
	"Client1": {
		"company": ["Company:", "Farmers"],
		"fname":   ["First Name:", "Jason"],
		"lname":   ["Last Name:", "Woods"],
		"email":   ["Email", "jwoods@gmail.com"],
		"Auto":    ["Auto Insurance:", "yes"],
		"Moto":    ["motorcycle Insurance:", "no"],
		"rv":      ["RV Insurance:", "yes"],
		"home":    ["Home Insurance:", "yes"],
		"rent":    ["Renters Insurance:", "no"],
		"life":    ["Life Insurance:", "yes"],
		"numV":    ["Number of Vehicles:", "4"],
		"numPoliy":["Policy Number:", "12342345"],
		"comment": ["Additional Comments:", "This is a new Client"],
		"nDate":   ["Renewal Date:", "12/12/2014"]
		
	},
	"Client2": {
		"company": ["Company:", "State Farm"],
		"fname":   ["First Name:", "Joe"],
		"lname":   ["Last Name:", "Jordan"],
		"email":   ["Email", "jordans@gmail.com"],
		"Auto":    ["Auto Insurance:", "no"],
		"Moto":    ["motorcycle Insurance:", "yes"],
		"rv":      ["RV Insurance:", "yes"],
		"home":    ["Home Insurance:", "yes"],
		"rent":    ["Renters Insurance:", "no"],
		"life":    ["Life Insurance:", "yes"],
		"numV":    ["Number of Vehicles:", "4"],
		"numPoliy":["Policy Number:", "111133344"],
		"comment": ["Additional Comments:", "This is a new Client too"],
		"nDate":   ["Renewal Date:", "1/12/2014"]
		
	},
	"Client3": {
		"company": ["Company:", "Progressive"],
		"fname":   ["First Name:", "Katie"],
		"lname":   ["Last Name:", "Gunter"],
		"email":   ["Email", "kpg@gmail.com"],
		"Auto":    ["Auto Insurance:", "yes"],
		"Moto":    ["motorcycle Insurance:", "no"],
		"rv":      ["RV Insurance:", "yes"],
		"home":    ["Home Insurance:", "yes"],
		"rent":    ["Renters Insurance:", "no"],
		"life":    ["Life Insurance:", "yes"],
		"numV":    ["Number of Vehicles:", "4"],
		"numPoliy":["Policy Number:", "1122355566"],
		"comment": ["Additional Comments:", "This is a new Client aswell"],
		"nDate":   ["Renewal Date:", "5/12/2014"]
		
	},
	"Client4": {
		"company": ["Company:", "American"],
		"fname":   ["First Name:", "Kay"],
		"lname":   ["Last Name:", "Gooner"],
		"email":   ["Email", "kgooner@gmail.com"],
		"Auto":    ["Auto Insurance:", "yes"],
		"Moto":    ["motorcycle Insurance:", "yes"],
		"rv":      ["RV Insurance:", "yes"],
		"home":    ["Home Insurance:", "yes"],
		"rent":    ["Renters Insurance:", "no"],
		"life":    ["Life Insurance:", "yes"],
		"numV":    ["Number of Vehicles:", "3"],
		"numPoliy":["Policy Number:", "112554422"],
		"comment": ["Additional Comments:", "kay is great"],
		"nDate":   ["Renewal Date:", "04/16/2017"]
		
	},
	"Client5": {
		"company": ["Company:", "All State"],
		"fname":   ["First Name:", "Corbin"],
		"lname":   ["Last Name:", "Tunter"],
		"email":   ["Email", "CTunt@gmail.com"],
		"Auto":    ["Auto Insurance:", "yes"],
		"Moto":    ["motorcycle Insurance:", "no"],
		"rv":      ["RV Insurance:", "no"],
		"home":    ["Home Insurance:", "no"],
		"rent":    ["Renters Insurance:", "yes"],
		"life":    ["Life Insurance:", "no"],
		"numV":    ["Number of Vehicles:", "2"],
		"numPoliy":["Policy Number:", "112400099"],
		"comment": ["Additional Comments:", "Young will need life later."],
		"nDate":   ["Renewal Date:", "10/12/2015"]
		
	},
	"Client6": {
		"company": ["Company:", "Nation Wide"],
		"fname":   ["First Name:", "Jeff"],
		"lname":   ["Last Name:", "Gunter"],
		"email":   ["Email", "Jgun@gmail.com"],
		"Auto":    ["Auto Insurance:", "yes"],
		"Moto":    ["motorcycle Insurance:", "yes"],
		"rv":      ["RV Insurance:", "yes"],
		"home":    ["Home Insurance:", "yes"],
		"rent":    ["Renters Insurance:", "no"],
		"life":    ["Life Insurance:", "yes"],
		"numV":    ["Number of Vehicles:", "4"],
		"numPoliy":["Policy Number:", "1122350077"],
		"comment": ["Additional Comments:", "Older"],
		"nDate":   ["Renewal Date:", "5/19/2016"]
		
	},
	"Client7": {
		"company": ["Company:", "Progressive"],
		"fname":   ["First Name:", "Tanner"],
		"lname":   ["Last Name:", "Gunter"],
		"email":   ["Email", "TannerG@yahoo.com"],
		"Auto":    ["Auto Insurance:", "yes"],
		"Moto":    ["motorcycle Insurance:", "no"],
		"rv":      ["RV Insurance:", "no"],
		"home":    ["Home Insurance:", "no"],
		"rent":    ["Renters Insurance:", "no"],
		"life":    ["Life Insurance:", "no"],
		"numV":    ["Number of Vehicles:", "1"],
		"numPoliy":["Policy Number:", "1122354433"],
		"comment": ["Additional Comments:", "Son of Jeff Gunter"],
		"nDate":   ["Renewal Date:", "7/12/2018"]
		
	},
	"Client8": {
		"company": ["Company:", "Progressive"],
		"fname":   ["First Name:", "Katie"],
		"lname":   ["Last Name:", "Gunter"],
		"email":   ["Email", "kpg@gmail.com"],
		"Auto":    ["Auto Insurance:", "yes"],
		"Moto":    ["motorcycle Insurance:", "no"],
		"rv":      ["RV Insurance:", "yes"],
		"home":    ["Home Insurance:", "yes"],
		"rent":    ["Renters Insurance:", "no"],
		"life":    ["Life Insurance:", "yes"],
		"numV":    ["Number of Vehicles:", "4"],
		"numPoliy":["Policy Number:", "1122355566"],
		"comment": ["Additional Comments:", "This is a new Client aswell"],
		"nDate":   ["Renewal Date:", "5/12/2014"]
		
	},
	"Client9": {
		"company": ["Company:", "Progressive"],
		"fname":   ["First Name:", "Katie"],
		"lname":   ["Last Name:", "Gunter"],
		"email":   ["Email", "kpg@gmail.com"],
		"Auto":    ["Auto Insurance:", "yes"],
		"Moto":    ["motorcycle Insurance:", "no"],
		"rv":      ["RV Insurance:", "yes"],
		"home":    ["Home Insurance:", "yes"],
		"rent":    ["Renters Insurance:", "no"],
		"life":    ["Life Insurance:", "yes"],
		"numV":    ["Number of Vehicles:", "4"],
		"numPoliy":["Policy Number:", "1122355566"],
		"comment": ["Additional Comments:", "This is a new Client aswell"],
		"nDate":   ["Renewal Date:", "5/12/2014"]
		
	},
	"Client10": {
		"company": ["Company:", "Progressive"],
		"fname":   ["First Name:", "Katie"],
		"lname":   ["Last Name:", "Gunter"],
		"email":   ["Email", "kpg@gmail.com"],
		"Auto":    ["Auto Insurance:", "yes"],
		"Moto":    ["motorcycle Insurance:", "no"],
		"rv":      ["RV Insurance:", "yes"],
		"home":    ["Home Insurance:", "yes"],
		"rent":    ["Renters Insurance:", "no"],
		"life":    ["Life Insurance:", "yes"],
		"numV":    ["Number of Vehicles:", "4"],
		"numPoliy":["Policy Number:", "1122355566"],
		"comment": ["Additional Comments:", "This is a new Client aswell"],
		"nDate":   ["Renewal Date:", "5/12/2014"]
		
	},
	"Client11": {
		"company": ["Company:", "Progressive"],
		"fname":   ["First Name:", "Katie"],
		"lname":   ["Last Name:", "Gunter"],
		"email":   ["Email", "kpg@gmail.com"],
		"Auto":    ["Auto Insurance:", "yes"],
		"Moto":    ["motorcycle Insurance:", "no"],
		"rv":      ["RV Insurance:", "yes"],
		"home":    ["Home Insurance:", "yes"],
		"rent":    ["Renters Insurance:", "no"],
		"life":    ["Life Insurance:", "yes"],
		"numV":    ["Number of Vehicles:", "4"],
		"numPoliy":["Policy Number:", "1122355566"],
		"comment": ["Additional Comments:", "This is a new Client aswell"],
		"nDate":   ["Renewal Date:", "5/12/2014"]
		
	},
	"Client12": {
		"company": ["Company:", "Progressive"],
		"fname":   ["First Name:", "Katie"],
		"lname":   ["Last Name:", "Gunter"],
		"email":   ["Email", "kpg@gmail.com"],
		"Auto":    ["Auto Insurance:", "yes"],
		"Moto":    ["motorcycle Insurance:", "no"],
		"rv":      ["RV Insurance:", "yes"],
		"home":    ["Home Insurance:", "yes"],
		"rent":    ["Renters Insurance:", "no"],
		"life":    ["Life Insurance:", "yes"],
		"numV":    ["Number of Vehicles:", "4"],
		"numPoliy":["Policy Number:", "1122355566"],
		"comment": ["Additional Comments:", "This is a new Client aswell"],
		"nDate":   ["Renewal Date:", "5/12/2014"]
		
	},
	"Client13": {
		"company": ["Company:", "Progressive"],
		"fname":   ["First Name:", "Katie"],
		"lname":   ["Last Name:", "Gunter"],
		"email":   ["Email", "kpg@gmail.com"],
		"Auto":    ["Auto Insurance:", "yes"],
		"Moto":    ["motorcycle Insurance:", "no"],
		"rv":      ["RV Insurance:", "yes"],
		"home":    ["Home Insurance:", "yes"],
		"rent":    ["Renters Insurance:", "no"],
		"life":    ["Life Insurance:", "yes"],
		"numV":    ["Number of Vehicles:", "4"],
		"numPoliy":["Policy Number:", "1122355566"],
		"comment": ["Additional Comments:", "This is a new Client aswell"],
		"nDate":   ["Renewal Date:", "5/12/2014"]
		
	},
	"Client14": {
		"company": ["Company:", "Progressive"],
		"fname":   ["First Name:", "Katie"],
		"lname":   ["Last Name:", "Gunter"],
		"email":   ["Email", "kpg@gmail.com"],
		"Auto":    ["Auto Insurance:", "yes"],
		"Moto":    ["motorcycle Insurance:", "no"],
		"rv":      ["RV Insurance:", "yes"],
		"home":    ["Home Insurance:", "yes"],
		"rent":    ["Renters Insurance:", "no"],
		"life":    ["Life Insurance:", "yes"],
		"numV":    ["Number of Vehicles:", "4"],
		"numPoliy":["Policy Number:", "1122355566"],
		"comment": ["Additional Comments:", "This is a new Client aswell"],
		"nDate":   ["Renewal Date:", "5/12/2014"]
		
	},
	"Client15": {
		"company": ["Company:", "Progressive"],
		"fname":   ["First Name:", "Katie"],
		"lname":   ["Last Name:", "Gunter"],
		"email":   ["Email", "kpg@gmail.com"],
		"Auto":    ["Auto Insurance:", "yes"],
		"Moto":    ["motorcycle Insurance:", "no"],
		"rv":      ["RV Insurance:", "yes"],
		"home":    ["Home Insurance:", "yes"],
		"rent":    ["Renters Insurance:", "no"],
		"life":    ["Life Insurance:", "yes"],
		"numV":    ["Number of Vehicles:", "4"],
		"numPoliy":["Policy Number:", "1122355566"],
		"comment": ["Additional Comments:", "This is a new Client aswell"],
		"nDate":   ["Renewal Date:", "5/12/2014"]
		
	},
	"Client16": {
		"company": ["Company:", "Progressive"],
		"fname":   ["First Name:", "Katie"],
		"lname":   ["Last Name:", "Gunter"],
		"email":   ["Email", "kpg@gmail.com"],
		"Auto":    ["Auto Insurance:", "yes"],
		"Moto":    ["motorcycle Insurance:", "no"],
		"rv":      ["RV Insurance:", "yes"],
		"home":    ["Home Insurance:", "yes"],
		"rent":    ["Renters Insurance:", "no"],
		"life":    ["Life Insurance:", "yes"],
		"numV":    ["Number of Vehicles:", "4"],
		"numPoliy":["Policy Number:", "1122355566"],
		"comment": ["Additional Comments:", "This is a new Client aswell"],
		"nDate":   ["Renewal Date:", "5/12/2014"]
		
	},
	"Client17": {
		"company": ["Company:", "Progressive"],
		"fname":   ["First Name:", "Katie"],
		"lname":   ["Last Name:", "Gunter"],
		"email":   ["Email", "kpg@gmail.com"],
		"Auto":    ["Auto Insurance:", "yes"],
		"Moto":    ["motorcycle Insurance:", "no"],
		"rv":      ["RV Insurance:", "yes"],
		"home":    ["Home Insurance:", "yes"],
		"rent":    ["Renters Insurance:", "no"],
		"life":    ["Life Insurance:", "yes"],
		"numV":    ["Number of Vehicles:", "4"],
		"numPoliy":["Policy Number:", "1122355566"],
		"comment": ["Additional Comments:", "This is a new Client aswell"],
		"nDate":   ["Renewal Date:", "5/12/2014"]
		
	},
	"Client18": {
		"company": ["Company:", "Progressive"],
		"fname":   ["First Name:", "Katie"],
		"lname":   ["Last Name:", "Gunter"],
		"email":   ["Email", "kpg@gmail.com"],
		"Auto":    ["Auto Insurance:", "yes"],
		"Moto":    ["motorcycle Insurance:", "no"],
		"rv":      ["RV Insurance:", "yes"],
		"home":    ["Home Insurance:", "yes"],
		"rent":    ["Renters Insurance:", "no"],
		"life":    ["Life Insurance:", "yes"],
		"numV":    ["Number of Vehicles:", "4"],
		"numPoliy":["Policy Number:", "1122355566"],
		"comment": ["Additional Comments:", "This is a new Client aswell"],
		"nDate":   ["Renewal Date:", "5/12/2014"]
		
	},
	"Client19": {
		"company": ["Company:", "Progressive"],
		"fname":   ["First Name:", "Katie"],
		"lname":   ["Last Name:", "Gunter"],
		"email":   ["Email", "kpg@gmail.com"],
		"Auto":    ["Auto Insurance:", "yes"],
		"Moto":    ["motorcycle Insurance:", "no"],
		"rv":      ["RV Insurance:", "yes"],
		"home":    ["Home Insurance:", "yes"],
		"rent":    ["Renters Insurance:", "no"],
		"life":    ["Life Insurance:", "yes"],
		"numV":    ["Number of Vehicles:", "4"],
		"numPoliy":["Policy Number:", "1122355566"],
		"comment": ["Additional Comments:", "This is a new Client aswell"],
		"nDate":   ["Renewal Date:", "5/12/2014"]
		
	},
	"Client20": {
		"company": ["Company:", "Progressive"],
		"fname":   ["First Name:", "Katie"],
		"lname":   ["Last Name:", "Gunter"],
		"email":   ["Email", "kpg@gmail.com"],
		"Auto":    ["Auto Insurance:", "yes"],
		"Moto":    ["motorcycle Insurance:", "no"],
		"rv":      ["RV Insurance:", "yes"],
		"home":    ["Home Insurance:", "yes"],
		"rent":    ["Renters Insurance:", "no"],
		"life":    ["Life Insurance:", "yes"],
		"numV":    ["Number of Vehicles:", "4"],
		"numPoliy":["Policy Number:", "1122355566"],
		"comment": ["Additional Comments:", "This is a new Client aswell"],
		"nDate":   ["Renewal Date:", "5/12/2014"]
		
	}
}